### PR TITLE
fix: add logic for when type is an array

### PR DESCRIPTION
**Pull request by brayden-bcgsc**

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thank you for contributing. 

Before I can merge this in we need to be sure that we are implementing valid Sequelize and that it will produce valid schemas. That is handled for the nullable string type shown at this line https://github.com/alt3/sequelize-to-json-schemas/blob/master/test/models/user.js#L68.

Could you extend the user model with something similar for your case and make sure the tests still pass? If you have any questions please let me know 👍

**Comment by bravo-kernel** [comment]
Please add an additional one (instead of changing the existing one) so the old test remains unchanged.

**Comment by bravo-kernel** [comment]
@brayden-bcgsc I just [added a separate model property](https://github.com/alt3/sequelize-to-json-schemas/blob/master/test/models/user.js#L48) using the change you proposed here and to my surprise... that test succeeds without code changes and thus without your fix.

If you think your fix should be in and is valid, please update the sequelize user-model pointed to above so that it breaks and requires/hits your fix, you can verify that in the code coverage results.

_Please star ⭐️ if you like the lib_

**Comment by bravo-kernel** [comment]
Simply put: what Sequelize model definition brought you to suggesting this fix?

**Comment by brayden-bcgsc** [comment]
The issue I am having is when the datatype is JSONB and allowNull is true. The schema that is created is this
```
"type": [
   [
        "object",
        "array",
        "boolean",
        "number",
        "string"
    ],
    "null"
 ],
```
Which isn't a valid schema type. I was trying to fix it so, that if type is already an array 'null' would be appended to the current array instead of type and 'null' added to a new array.

**Comment by bravo-kernel** [comment]
I see, I saw this passing by as well when I was testing so I assumed it could be something like this. 

Thanks for hanging in here ❤️

**Pull request merged**
