### PR TITLE
Add Attribute Level Schema Override

### PR DESCRIPTION
**Pull request by robbyphillips**
Allow the addition of a `jsonSchema.schema` property on sequelize model attributes that will
override the type generated by the TypeMapper class.  This is important for any type that is mapped
to the TypeMapper's internal `ANY` type when using the OpenAPI strategy.

One Potential improvement that does not fit nicely into the current setup would be to throw strategy
specific errors when this override is required to produce a valid output, but unfortunately the
strategy class is only called by the TypeMapper class if we need to get a nullable version of the
type.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
This is an awesome contribution, thanks, merging straight in. 

Since you are the first contributor/sign-of-usage ever:

1. how hard/easy was it to contribute/understand the code?
2. do you see improvements?
3. how about breaking the github zero-star status ;)

**Comment by bravo-kernel** [comment]
While I was googling how to merge with a changed commit status I noticed the README has not been updated. Do you think this change could appear somewhere?

**Comment by bravo-kernel** [comment]
Thanks, I will merge once the check turn green. 

FYI I need to rename the commit message so the continuous deployment works as expected. This repo follows https://www.conventionalcommits.org/en/v1.0.0/ for that.

**Comment by robbyphillips** [comment]
Ah, good point.  README updated! 

And that's great!  It's been really nice to contribute when you're super responsive.  Sorry I didn't catch the branch naming convention.

As for your questions:
1.  Not too bad.  I was a little confused at first how exactly the strategies were used, but the main schema manager class is pretty straightforward to read through.
2.  Nothing super specific, but there might be a better way to relate the `TypeMapper` to the strategy classes to give a little more control over the generated type output based on differences like the one that inspired this pr.
3. Haha, for sure.

**Comment by bravo-kernel** [comment]
As you can see I just merged the PR and if things go well a new release will be published to npm soon.

Thanks for the feedback. I understand the strategies take more time to understand but glad you did figure it out. Hope the advantages of that design choice make sense a well. I wrote it as a show-case for proper strategy-pattern while learning js and I think it worked out well. Creating a new schema variant is now super simple, seven functions and be done with it.

Any way, highly appreciate your contribution. Hope it proves useful to you.

**Comment by bravo-kernel** [comment]
It's there, including your readme update 💃

https://www.npmjs.com/package/@alt3/sequelize-to-json-schemas

Signing off now, thanks again!

**Pull request merged**
