### PR TITLE
Fix issue when type is an array

### PR DESCRIPTION
**Pull request by brayden-bcgsc**
Refs #51

### CODE REVIEW

**Comment by bravo-kernel** [comment]
This is a pretty amazing contribution, thank you kindly ❤️. If the linting gets solved I will merge this straight in and a new release should become live within minutes.

**Comment by bravo-kernel** [comment]
I think I will have to spend some time improving/fixing husky so that these things get caught before committing (as this has happened to me multiple times as well)

**Comment by brayden-bcgsc** [comment]
I also have a question about why do you use https for referencing the schema draft version?

```
  getPropertySchema() {
    return {
      $schema: 'https://json-schema.org/draft-07/schema#',
    };
  }
``` 
I'm not exactly sure which is the correct way, but it seems like http is because Ajv only supports the http version of the schema draft. Your validation tests are even run against the http version of schema draft. 

 ```
    // ------------------------------------------------------------------------
    // confirm the document is valid JSON Schema Draft-07
    // ------------------------------------------------------------------------
    describe('Ensure that the resultant document:', function() {
      it('successfully validates as JSON Schema Draft-07', async () => {
        expect.assertions(1);

        // validate document using ajv
        const ajv = new Ajv();

        const valid = ajv.validate('http://json-schema.org/draft-07/schema#', schema);
        if (!valid) {
          console.log(ajv.errors); // eslint-disable-line no-console
        }

        expect(valid).toBe(true);
      });
    });
```

Is there a reason for this?

**Comment by bravo-kernel** [comment]
Nothing specific comes to mind right now except the fact that both seem to be available for downloading, I guess I just chose the secure version (and yes, f*** up consistency in that test).

**Comment by bravo-kernel** [comment]
Could possibly be a good configuration option for the SchemaManager. Something like `ssl: true` or similar. Would that help you out, I noticed a change in your code IIRC.

**Comment by bravo-kernel** [comment]
Last thing for now, I'm really sorry but I have to go in about 5 minutes. I will be available to look at this again tomorrow.

**Comment by brayden-bcgsc** [comment]
I'll fix the linting errors when I'm back on Monday. The http version of the schema draft would be very helpful.

**Comment by bravo-kernel** [comment]
Awesome, I will await Monday for this one. Some additional honest feedback:

- I remember reasoning about the https schema, specifically thinking about possible "mixed content/unsafe" browser warnings when serving the OpenAPI web interface using HTTPS but the schema being HTTP. Could be total BS but hey, that was the reason
- should have been an option straight away but I probably forgot about it alltogether

I will see if I can come up with something for that this weekend

**Comment by bravo-kernel** [comment]
Thanks for this contribution @brayden-bcgsc, highly appreciated, A new release should be available in a couple of minutes, please ⭐️ if you like.

>  I think I have a nice solution for the http/https schema switching, just need to find some time to properly implement it. Will probably happen this weekend so perhaps best to keep an eye on the releases.

**Pull request merged**
